# Generated by Django 3.2.5 on 2021-07-23 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('rule_num', models.PositiveIntegerField(choices=[(5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='Number of players', primary_key=True, serialize=False)),
                ('tasks', models.CharField(help_text='Task Rule', max_length=20)),
            ],
            options={
                'ordering': ['rule_num'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.PositiveIntegerField(help_text='Room id(e.g. 1234)', primary_key=True, serialize=False)),
                ('player_num', models.PositiveIntegerField(default=0, help_text='Players in the room')),
                ('Lady_in_the_lake', models.BooleanField(help_text='Whether a lady in the lake is included in the game')),
                ('status', models.CharField(choices=[('WAIT', 'Waiting...'), ('PLAY', 'Playing...'), ('READY', 'Ready!')], default='WAIT', help_text='Room status(waiting/playing/ready)', max_length=10)),
                ('max_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.rule')),
            ],
            options={
                'ordering': ['room_id'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_name', models.CharField(help_text='Player nick name', max_length=20, primary_key=True, serialize=False)),
                ('id', models.PositiveIntegerField(help_text='seat id')),
                ('role', models.CharField(choices=[('Merlin', 'Merlin'), ('Percival', 'Percival'), ('Servant', 'Loyal Servant of Author'), ('Morgana', 'Morgana'), ('Assassin', 'Assassin'), ('Minion', 'Minion of Mordred'), ('Oberon', 'Oberon'), ('Mordred', 'Mordred')], default='Servant', help_text='Role of each player', max_length=20)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.room')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
