# Generated by Django 3.2.5 on 2021-07-26 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210726_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['id'], 'permissions': (('Room holder', ' set a player as a Room holder'),)},
        ),
    ]
