# Generated by Django 3.2.5 on 2021-07-26 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_player_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['id'], 'permissions': (('room_holder', ' set a player as a Room holder'),)},
        ),
    ]
