# Generated by Django 3.2.5 on 2021-07-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_player_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='action',
            field=models.BooleanField(default=True, help_text='Your action for each mission'),
        ),
        migrations.AddField(
            model_name='player',
            name='vote',
            field=models.BooleanField(default=True, help_text='Your vote each round'),
        ),
    ]
