# Generated by Django 3.2.5 on 2021-07-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210728_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='action',
            field=models.BooleanField(default=True, help_text='Check if you decide to complete the mission. Please check if you are not in the mission'),
        ),
        migrations.AlterField(
            model_name='player',
            name='vote',
            field=models.CharField(choices=[('agree', 'I agree with the chief!'), ('disagree', 'I don`t agree with the chief!')], default='agree', help_text="Choose 'agree' if the chief`s proposal sounds OK for you.", max_length=20),
        ),
    ]
