# Generated by Django 3.2.5 on 2021-07-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_player_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='vote',
            field=models.CharField(choices=[('agree', 'I agree with the chief!'), ('disagree', 'I don`t agree with the chief!')], default='agree', help_text="Choose 'agree' if the chief`s proposal sounds OK for you.", max_length=20),
        ),
    ]
