# Generated by Django 3.2.5 on 2021-07-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_player_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='action',
            field=models.CharField(choices=[('PASS', 'PASS'), ('OUT', 'OUT'), ('FAIL', 'FAIL')], default='OUT', help_text='PASS if you decide to complete the mission. FAIL if you decide otherwise. OUT if you are not in the mission!', max_length=10),
        ),
    ]
