# Generated by Django 3.2.5 on 2021-07-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_player_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='roles',
            field=models.CharField(help_text='Roles for each player', max_length=50, null=True),
        ),
    ]
