# Generated by Django 3.2.5 on 2021-07-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_rule_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='vote',
            field=models.CharField(choices=[('agree', 'agree'), ('disagree', 'disagree'), ('hesitate...', 'hesitate...')], default='hesitate...', help_text="Choose 'agree' if the chief`s proposal sounds OK for you.", max_length=20),
        ),
        migrations.AlterField(
            model_name='rule',
            name='roles',
            field=models.CharField(help_text='Roles for each player', max_length=150, null=True),
        ),
    ]
